### ISSUE TITLE
Sizes of course selector for different devices widths

### ISSUE THREAD

**Issue by miguelHx** [miguelHx/Bobcat-Courses#7]
For mobile devices, collapse dept/course dropdown menus
```css
.course-selector__container {
  max-width: 18.75rem; /* 300px */
  margin: 0 auto;
}
```
For desktop,
```css
.course-selector__container {
  max-width: // still deciding, depends on how much room the table takes up on the right.
}
```
